### ISSUE TITLE
API design suggestion: Avoid `bool` parameter to `Span::new`

### ISSUE THREAD

**Issue by scouten** [JulesGuesnon/nom-span#1]
First, thank you for creating this crate. Looks like it will be useful for a project I'm experimenting with (AsciiDoc parsing), so I'm excited to put it to work.

I want to suggest a small design shift in your `Span::new` function which I think will help readability at the call sites: When I'm reading the call site, I have no idea what `true` or `false` means without looking at the `Span` documentation.

I can think of two alternatives:

1. Split `Span::new` into two new functions `Span::new_for_utf8` and `Span::new_for_ascii` (naming help welcome)
2. Replace the `bool` parameter with a `enum Encoding` which has `Utf8` and `Ascii` variants.

Hope this helps!

(P.S. My thinking roughly aligns with [this article from Alex Kondov](https://alexkondov.com/should-you-pass-boolean-to-functions/).)

**Comment by JulesGuesnon** [comment]
Hey @scouten, thanks for the issue! 
I think that your raising a good point. Not sure about what the naming should be, but having `ascii` or `utf8` in it would be quite explicit and easy to understand I think. I'll be busy today, so I'll probably have a look tomorrow

**Comment by JulesGuesnon** [comment]
I guess it was not exactly tomorrow, but it ended up implemented the way you suggested before the 1 year of this issue at least. Sorry for the delay
